export const GET_MOVIE_LIST_NOW_SHOWING = 'GET_MOVIE_LIST_NOW_SHOWING';
export const GET_MOVIE_LIST_UP_COMING = 'GET_MOVIE_LIST_UP_COMING';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GET_MOVIE_DETAIL_CLUSTER = 'GET_MOVIE_DETAIL_CLUSTER';
export const REMOVE_CURRENT_MOVIE_DETAIL = 'REMOVE_CURRENT_MOVIE_DETAIL';
